# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YiLive' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for YiLive

  target 'YiLiveTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'YiLiveUITests' do
    inherit! :search_paths
    # Pods for testing
      pod "AFNetworking"
    #一行代码即可刷新UItableView和collectionView
      pod "MJRefresh"
    #各种提示和进度条提示
    pod "MBProgressHUD"
    #webView脚本桥接
      pod "WebViewJavascriptBridge"
     
  end

end
